name: ä¸œä¸œå·¥å‚ğŸ­

on:
    workflow_dispatch:
    schedule:
        - cron: "30 18,23 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_jdfactory

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: æ‹‰å–ä»£ç 
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: å®‰è£…ä¾èµ–åŒ…
              run: |
                  npm install
            - name: "è¿è¡Œã€ä¸œä¸œå·¥å‚ğŸ­ã€‘"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  JD_USER_AGENT: ${{ github.event.client_payload.JD_USER_AGENT || secrets.JD_USER_AGENT }}
                  PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ github.event.client_payload.BARK_SOUND || secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ github.event.client_payload.DD_BOT_TOKEN || secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ github.event.client_payload.DD_BOT_SECRET || secrets.DD_BOT_SECRET }}
                  IGOT_PUSH_KEY: ${{ github.event.client_payload.IGOT_PUSH_KEY || secrets.IGOT_PUSH_KEY }}
                  QQ_SKEY: ${{ github.event.client_payload.QQ_SKEY || secrets.QQ_SKEY }}
                  QQ_MODE: ${{ github.event.client_payload.QQ_MODE || secrets.QQ_MODE }}
                  QYWX_KEY: ${{ github.event.client_payload.QYWX_KEY || secrets.QYWX_KEY }}
                  QYWX_AM: ${{ github.event.client_payload.QYWX_AM || secrets.QYWX_AM }}
                  PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}
                  FACTORAY_WANTPRODUCT_NAME: ${{ github.event.client_payload.FACTORAY_WANTPRODUCT_NAME || secrets.FACTORAY_WANTPRODUCT_NAME }}
                  DDFACTORY_SHARECODES: ${{ github.event.client_payload.DDFACTORY_SHARECODES || secrets.DDFACTORY_SHARECODES }}
                  SYNCURL: https://github.com/jackpater/jd_actions/raw/main/scripts/jd_jdfactory.js
                  #ä¸“å±é…ç½®
                  IGNORE_COOKIE_JDGC: ${{ github.event.client_payload.IGNORE_COOKIE_JDGC || secrets.IGNORE_COOKIE_JDGC }} #äº¬ä¸œå·¥å‚ç¦ç”¨æŸäº›cookieçš„æ‰§è¡Œ,å› ä¸ºé€šçŸ¥å¤ªçƒ¦äº†å‘€,æ¯”å¦‚è¦ç¦ç”¨ç¬¬2å’Œç¬¬å››ä¸ªçš„æ‰§è¡Œ,åˆ™å¡«å…¥[2,4]å³å¯,åŒ…å«ä¸­æ‹¬å·å“¦
                  JDFACTORY_FORBID_ACCOUNT: ${{ github.event.client_payload.JDFACTORY_FORBID_ACCOUNT || secrets.JDFACTORY_FORBID_ACCOUNT }}