# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: äº¬ä¸œä»»åŠ¡ï¼ˆæ¯æ—¥ä¸€æ¬¡ï¼‰ğŸ•

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/jackpater/TaskAction.git ~/TaskAction
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“å­˜ Actionã€‚
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ä½¿ç”¨ package-lock.json çš„ Hash ä½œä¸ºç¼“å­˜çš„ keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/TaskAction
          git checkout jd_code
          npm install

      - name: 'è¿è¡Œ ã€ç­¾åˆ°ã€‘'
        run: |
          cd ~/TaskAction
          node jd_bean_sign.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€äº¬å–œç­¾åˆ°ã€‘'
        run: |
          cd ~/TaskAction
          node jx_sign.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€äº¬å°è¶…å…‘æ¢å¥–å“ã€‘'
        run: |
          cd ~/TaskAction
          node jd_blueCoin.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€æ‘‡äº¬è±†ã€‘'
        run: |
          cd ~/TaskAction
          node jd_club_lottery.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€é¢†äº¬è±†é¢å¤–å¥–åŠ±ã€‘'
        run: |
          cd ~/TaskAction
          node jd_bean_home.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œå…¨æ°‘å¼€çº¢åŒ…ã€‘'
        run: |
          cd ~/TaskAction
          node jd_redPacket.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€è¿›åº—é¢†è±†ã€‘'
        run: |
          cd ~/TaskAction
          node jd_shop.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€ç­¾åˆ°é¢†ç°é‡‘ã€‘'
        run: |
          cd ~/TaskAction
          node jd_cash.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          JD_CASH_SHARECODES: ${{ secrets.JD_CASH_SHARECODES }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œæ±½è½¦ã€‘'
        run: |
          cd ~/TaskAction
          node jd_car.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œæ±½è½¦exchangeã€‘'
        run: |
          cd ~/TaskAction
          node jd_car_exchange.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€ä¸œä¸œå°çªã€‘'
        run: |
          cd ~/TaskAction
          node jd_small_home.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€ç–¯ç‹‚çš„joyã€‘'
        run: |
          cd ~/TaskAction
          node jd_crazy_joy.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          JDJOY_HELPSELF: ${{ github.event.client_payload.JDJOY_HELPSELF || secrets.JDJOY_HELPSELF }}
          JDJOY_APPLYJDBEAN: ${{ github.event.client_payload.JDJOY_APPLYJDBEAN || secrets.JDJOY_APPLYJDBEAN }}
          JDJOY_SHARECODES: ${{ github.event.client_payload.JDJOY_SHARECODES || secrets.JDJOY_SHARECODES }}          

      - name: 'è¿è¡Œ ã€äº¬ä¸œæ’è¡Œæ¦œã€‘'
        run: |
          cd ~/TaskAction
          node jd_rankingList.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€é‡‘èå…»çŒªã€‘'
        run: |
          cd ~/TaskAction
          node jd_pigPet.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€åå…ƒè¡—ã€‘'
        run: |
          cd ~/TaskAction
          node jd_syj.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œå¿«é€’ã€‘'
        run: |
          cd ~/TaskAction
          node jd_kd.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œèµšèµšã€‘'
        run: |
          cd ~/TaskAction
          node jd_jdzz.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€ç›²ç›’æŠ½äº¬è±†ã€‘'
        run: |
          cd ~/TaskAction
          node jd_sgmh.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œç§’ç§’å¸ã€‘'
        run: |
          cd ~/TaskAction
          node jd_ms.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€æºå¤´å¥½ç‰©çº¢åŒ…ã€‘'
        run: |
          cd ~/TaskAction
          node jd_coupon.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œè¶…çº§ç›’å­ã€‘'
        run: |
          cd ~/TaskAction
          node jd_super_box.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 'è¿è¡Œ ã€å°é¸½æœ‰ç¤¼ã€‘'
        run: |
          cd ~/TaskAction
          node jd_xg.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      
      - name: 'è¿è¡Œ ã€äº¬ä¸œæŠ½å¥–æœºã€‘'
        run: |
          cd ~/TaskAction
          node jd_lotteryMachine.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


