# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Á¨ëË∞±üòÄ

on:
    workflow_dispatch:
    schedule:
        - cron: "*/15 0-15 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'ËøêË°å „ÄêÁ¨ëË∞±üòÄ‚Äç„Äë'
              run: |
                  node onlyOneExecute.js
              env:
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN2 }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID2 }}
                  XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN2 }}
                  XP_iboxpayvideoHEADER: ${{ secrets.XP_iboxpayvideoHEADER2 }}
                  XP_iboxpayvideoBODY: ${{ secrets.XP_iboxpayvideoBODY2 }}
                  XP_CASH: ${{ secrets.XP_CASH }}
                  XP_live: ${{ secrets.XP_live }}
                  SYNCURL: https://github.com/jackpater/App_auto/raw/ziye/Task/iboxpay.js